name: Bump version

on:
  push:
    branches: [main]

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install commitizen

      - name: Setup Git user to push new tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump new version
        shell: bash
        run: |
          git fetch
          cz bump --check-consistency --changelog --yes

      - name: Push new tag back to GitHub
        shell: bash
        run: |
          git push --tags
