name: Bump version

on:
  workflow_dispatch:
    inputs:
      part:
        description: "New version of project (major | minor | patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      new_version:
        description: "New version to bump to"
        required: true
jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install tbump

      - name: Setup Git user to push new tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump new version
        shell: bash
        run: |
          tbump --non-interactive --no-push ${{ github.event.inputs.new_version }}

      - name: Push new tag back to GitHub
        shell: bash
        run: |
          git push origin main --tags
